### ISSUE TITLE
Next and previous buttons...

### ISSUE THREAD

**Issue by secretGeek** [atomcorp/themes#3]
...would help when looking through these wonderful themes. 

Thank you.

**Comment by atomcorp** [comment]
Hey, thanks for the suggestion! 

I tried to make the site accessible, so you can tab around and use arrow keys. But that only works in the list when it's focused and since i've hidden the fact it's radio buttons it's not very clear. Also, I'm not sure if you're referring to desktop of mobile, but there's no way to quickly look through on mobile.

So I like the idea of having keyboard shortcuts (A+D) and on screen promts/buttons for previous/next, and also adding left/right swiping for mobile.

I'm in the middle of building a nicer UI atm, so I'll try an incorporate these.

Thanks so much!

**Comment by secretGeek** [comment]
I was visiting from Mobile (iOS) and hadn't seen the experience from Desktop. I just visited from desktop and I can use up down to move through all the theme. Woah, I love that!

**Comment by atomcorp** [comment]
This got wrapped up with a whole other update which is why it took so long, but you can now cycle through the themes by either hitting the Prev and Next buttons or by pressing A and D!

Thanks again for the suggestion @secretGeek !
