### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jos3s** [atomcorp/themes#8]
It would be interesting if in the themes added directly from this repository a small message was added in the theme view, with the name of the person who added that theme

**Comment by atomcorp** [comment]
Hey! Yeah I think something like this would be a good idea, I'd like to find a way to credit the creators of the themes and/or anyone who ports them over.

The credits to most of these themes though [live in an unhelpful txt format on the repo ](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/README.md#credits)this site uses...

**Comment by Savvasun** [comment]
Would it be possible to put the names of the creators **next to the themes** in the bar on the top of the page?

It could be a good start and I think could be implemented.

**Comment by Savvasun** [comment]
Should the names of the creators be in a separate tab? Or should we just stick it in there?

**Comment by Savvasun** [comment]
I would be glad to hear if anybody wants to or implemented this feature. Meanwhile, I am working on **my own way of doing this** on [my fork of the repo](https://github.com/Savvasun/themes/tree/develop).

**Comment by atomcorp** [comment]
Hey @Savvasun thanks for taking an interest!

I don't know if I have much time this week to look into it, but I had made a bit of a start which you may find useful. It's on a branch I just uploaded called credit. I was just messing round trying to extract the authors and themes from the readme in the iterm2 repo. The problems I saw is who the author is can be messy, and sometimes other people need crediting for various reasons. It's not ver neat.

I would like the theme objects to have a metadata property that hosts info like creator, porter, dark/light etc. 

I would also quite like the credits to live in their own json file, and then maybe get the owner of the iterm2 repo to adopt it so it could be consumed more easily here and elsewhere 🤷‍♀️

Anyway, just my thoughts. Thanks again for your effort and have fun!

**Comment by Savvasun** [comment]
Hello @atomcorp,

Just so you know, all my work on this is on a branch called `develop` on [my fork of the repo](https://github.com/Savvasun/themes/projects/1).

>The problems I saw is who the author is can be messy, and sometimes other people need crediting for various reasons. It's not very neat.

I am currently working on a small program in Python that can extract info with the basic syntax. I have encountered issues with accuracy, but I have *many* ideas on how to fix them, so that's not an issue.

>I would like the theme objects to have a metadata property that hosts info like creator, porter, dark/light, etc.

I'm not sure how to do that now, but I feel it can be implemented.

>I would also quite like the credits to live in their own json file, and then maybe get the owner of the iterm2 repo to adopt it so it could be consumed more easily here and elsewhere 🤷‍♀️

My system currently just ports the info into a simple `.txt` file, which I think can also be accessed easily by the languages used in this repo.

If you want to look at my work, I am going to be mentioning some of my commits in this issue.

Here is a small example of the text file my code has extracted:

```
Violet:[ashfinal](https://github.com/ashfinal/vim-colors-violet).




synthwave:[brettstil](https://github.com/brettstil/)






Monokai:[vitalymak](https://github.com/vitalymak/iTerm2-Color-Schemes).

Neopolitan:[daytonn](https://github.com/daytonn/iTerm2-Color-Schemes)

Subliminal:[gdsrosa](https://github.com/gdsrosa/subliminal-itermcolors)



Spacedust:[mhallendal](https://github.com/mhallendal/spacedust-theme)

Mathias:[mathiasbynens](https://github.com/mathiasbynens/dotfiles)

LiquidCarbon:[markcho](https://github.com/markcho/iTerm2_LiquidCarbon)

NightLion:[Curvve

Tomorrow:[chriskempson](https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2)

Tomorrow:[ashwinv11](https://github.com/ashwinv11/)

Twilight:[stefri](https://gist.github.com/stefri/1183140)

Teerb:[Teerb](https://gist.github.com/teerb/1360453)


Misterioso:[flooose](https://github.com/flooose/misterioso-iterm2)



Shades:[fr3fou](https://github.com/fr3fou)




Cobalt2:[wesbos](https://github.com/wesbos/Cobalt2-iterm)

Operator:[dreamyguy](https://github.com/dreamyguy/iterm-theme-operator-mono-dark)

WarmNeon:[firewut](https://github.com/firewut)

SpaceGray:[ryentzer](https://github.com/ryentzer/SpaceGray-iTerm)

Jellybeans:[qtpi](https://github.com/qtpi/Jellybeans.itermcolors)

PaulMillr:[paulmillr](https://github.com/paulmillr/dotfiles/tree/master/terminal)

Harper:[idleberg](https://github.com/idleberg/Harper-iTerm2)

CLRS:[jasonlong](https://github.com/jasonlong/iterm-clrs)

Dracula:[zenorocha](https://github.com/zenorocha/dracula-theme)

themes:[zdj](https://github.com/zdj/themes/tree/master/iterm2)

Japanesque:[aereal](https://github.com/aereal/dotfiles/blob/master/colors/Japanesque/Japanesque.itermcolors)

Seti:[jesseweed](https://github.com/jesseweed/seti-syntax/)

Hipster:[Unkulunkulu](https://github.com/Unkulunkulu)

Chalk:[achalv](https://github.com/achalv/chalk)

Pencil:[mattly](https://github.com/mattly/iterm-colors-pencil)

Flat:[ahmetsulek](https://github.com/ahmetsulek/flat-terminal)

Atom,:[bahlo](https://github.com/bahlo/iterm-colors)

Afterglow:[yabatadesign](https://github.com/YabataDesign/afterglow-itermcolors)

Broadcast:[vinkla](https://github.com/vinkla/broadcast-theme)

Arthur,:[baskerville](https://github.com/baskerville/iTerm-2-Color-Themes)

Belafonte:[idleberg](https://github.com/idleberg)

3024:[0x3024](https://github.com/0x3024)

Argonaut:[effkay](https://github.com/effkay/iTerm-argonaut)

Espresso:[jurgemaister](https://github.com/jurgemaister/Espresso-Libre)

Hardcore:[hardcore](https://github.com/hardcore/iTerm-colors)

Rippedcasts:[mdw123](https://github.com/mdw123/rippedcasts)

Solorized:[heisters](https://gist.github.com/heisters/1015503)

VibrantInk:[asanghi](https://github.com/asanghi/vibrantinklion)

Wez:[wez](https://gist.github.com/wez/850268/)

Wombat:[djoyner](https://github.com/djoyner/iTerm2-wombat)

WildCherry:[mashaal](https://github.com/mashaal/wild-cherry)

Flatland:[realchaseadams](http://www.snip2code.com/Snippet/148193/Flatland-color-scheme-for-iTerm2)

Neutron:[Ch4s3](https://github.com/Ch4s3/iTerm2-Neutron)

Fideloper:[Fideloper](http://fideloper.com/)

Later:[vilhalmer](https://github.com/vilhalmer/System/tree/master/terminal-themes)

Galaxy:[jglovier](https://github.com/jglovier/galaxy-theme-iterm)

Slate:[deneshshan](https://github.com/deneshshan)

SpaceGray:[mhkeller](https://github.com/mhkeller/spacegray-eighties-iterm)

Borland:[delip](https://gist.github.com/delip/9e16c606d9331d69d681)

Cobalt:[vazquez](https://github.com/vazquez/cobalt-neon-iterm)

AtelierSulphurpool:[atelierbram](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/sulphurpool/)

Batman,:[pyrophos](https://github.com/pyrophos)

ENCOM:[Josh

Floraverse:[papayakitty](http://floraverse.com/)

Material:[stoeffel](https://github.com/stoeffel/material-iterm)

OceanicMaterial:[rahulpatel](https://github.com/rahulpatel)

MaterialOcean:[fr3fou](https://github.com/fr3fou)

AtomOneLight:[iamstarkov](https://github.com/iamstarkov)

Piatto:[kovv](https://github.com/kovv)


DuoTone:[chibicode](http://chibicode.com)

JetBrains:[vitstr](https://github.com/vitstr)

Bright:[tw15egan](https://github.com/tw15egan)

Ubuntu:default

Under:[peterpme](https://github.com/peterpme)

One:[sonph](https://github.com/sonph),

FirefoxDev:[Or3stis](https://github.com/Or3stis)

Ryuuko:[dylanaraps](https://github.com/dylanaraps)

Firewatch:[Sebastian

Pandora:[milosmatic](https://github.com/milosmatic/Pandora-iterm)

Elementary:[elementary.io](https://elementary.io/)

Gruvbox:[morhetz](https://github.com/morhetz)

Ayu:[alebcay](https://github.com/alebcay)

Deep:[ADoyle](https://github.com/adoyle-h)

Red:[ibrokemypie](https://github.com/ibrokemypie)

Tango:[crowsonkb](https://github.com/crowsonkb),

Pro:[crowsonkb](https://github.com/crowsonkb)

Fahrenheit:[jonascarpay](https://github.com/jonascarpay)

Calamity:[Pustur](https://github.com/Pustur)

Purple:[DeChamp](https://github.com/dechamp)

Purple:[msorre2](https://github.com/msorre2)

ChallengerDeep:[eendroroy](https://github.com/eendroroy)

Hopscotch:[Jan

Hivacruz:[Yann

Nocturnal:[Shriram


Whimsy:[Rod](https://github.com/rod)

Chester:[KH](https://github.com/spectralkh)

Django:[Jannis

DjangoSmoothy:[Jannis

DjangoRebornAgain:[christopherscott](https://github.com/christopherscott/django-reborn)

Kolorit:[thomaspaulmann](https://github.com/thomaspaulmann)

Cyberpunk:[Murderlon](https://github.com/Murderlon/cyberpunk-iterm)

LoveLace:[nalanbar](https://github.com/nalanbar)

Framer:[markogresak](https://github.com/markogresak)

Lab:[theatlasroom](https://github.com/theatlasroom)

Unikitty:[jakebathman](https://github.com/jakebathman)

Primary:[jayanthkoushik](https://github.com/jayanthkoushik)

Andromeda:[memije](https://github.com/memije)

Night:[praveenpuglia](https://github.com/praveenpuglia)

Midnight:[OberstKrueger](https://github.com/oberstkrueger)

Breeze:[KDE](https://kde.org)

coffee:[cbitterfield](https://github.com/cbitterfield)


Blueberry:[ReagentX](https://github.com/ReagentX)

BlueBerry:[murmurlilia](https://www.instagram.com/the.julias/)

Synthwave:[smithbm2316](https://github.com/smithbm2316)

Sakura:[0xN0ri](https://github.com/0xN0ri)

Mirage:[Tristan

Rouge:[Josef
```

It's laggy, sure, but it's a start.

**Comment by Savvasun** [comment]
I have converted the output to `.json` instead of `.txt`.

**Comment by Savvasun** [comment]
Unfortunately, when trying to copy part of @atomcorp's code, the `request()` part just can't see the file no matter what I do. I can simply use my own code, but it is much less efficient than the JavaScript. I'm thinking of using the same algorithm in my own code. It may be easier.

**Comment by Savvasun** [comment]
#### Update!

I have shortened my Python script, but RegEx doesn't seem to work, and multi-word theme names aren't fully supported. I couldn't work on this before as I was busy.

**Comment by Savvasun** [comment]
# Update!

I was finally able to implement ReGex! The code is much more efficient now and works perfectly. I am thinking of opening a **pull request** to actually *start* implementing the feature.

**Comment by atomcorp** [comment]
Hay Savvasun, thanks for all your enthusiasm and hard work! I'd really like to accept your contribution, but I'd like to just try and focus things.

The app is pretty automated currently, I have a NodeJS server running a script every day which pulls all the Windows Terminal themes from the iterm2-themes repo and combines it with a JSON of themes people have contributed in this repo. It would be nice if the credits could coexist with this process, which means the credits would have to support the external repo and this one. I don't think it's possible to reliably automate gathering the credits from item2-themes, due to how it holds them, but manually scraping them occasionally is better than nothing. 

In practice how I think this should work is in the file [`server/get-themes.js`](https://github.com/atomcorp/themes/blob/master/server/get-themes.js), when it gets the latest theme files, it checks each theme against a credits JSON file, and assigns any relevant credits as a property. It sort of does this already to check whether a theme is dark or light, for example. The file should probably live in the same place as [`app/src/custom-colour-schemes.json`](https://github.com/atomcorp/themes/blob/master/app/src/custom-colour-schemes.json).

So I think what I would be really interested in accepting is one or more of the following:

- a JSON file with the credits data that can be reasonably easily mapped to the themes
- amending [`server/get-themes.js`](https://github.com/atomcorp/themes/blob/master/server/get-themes.js) so it adds the credit JSON to themes output in [`server/themes.json`](https://github.com/atomcorp/themes/blob/master/server/themes.json)
- updating the frontend app code to display credits somewhere
- a JS script to automate the credits JSON file somewhat, pulling it from both the external item2 repo and this one


@Savvasun it sounds to me like you've done the first one, creating the JSON of credits, so maybe focus a pull request on that first. I don't think I can accept things that need Python, I don't know much about it and I'd like the project to be self-contained with a simple `yarn` / `npm install`. But if you can translate what you did into JS maybe that could be another pull request. Also appreciate it's a Git thing, but it's quite hard to see what you added in the pull request as is, so maybe start a fresh branch?!

But thanks again for putting some much time and effort into the project, it's really cool! Let me know if you need anymore info!

**Comment by atomcorp** [comment]
Got around to this finally. Credits should be viewable for themes added here, or scraped from iterm2 repo
